#!/bin/sh

git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"
mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
sudo pacman -S alacritty starship polybar picom dunst rofi pipewire pipewire-pulse spotifyd pipewire-audio wireplumper ranger easyeffects mpv zsh dex feh scrot 
mkdir ~/git
git clone https://aur.archlinux.org/paru.git ~/git/paru
cd ~/git/paru
makepkg -si
cd ~
paru -S xcwd-git xidlehook betterlockscreen
