#!/bin/sh

git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"
mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
if command -v pacman >/dev/null 2>&1; then
        sudo pacman -S alacritty starship polybar picom dunst rofi pipewire pipewire-pulse spotifyd pipewire-audio wireplumper ranger easyeffects mpv zsh dex feh scrot nerdfonts 
        mkdir ~/git
        git clone https://aur.archlinux.org/paru.git ~/git/paru
        cd ~/git/paru
        makepkg -si
        cd ~
        paru -S xcwd-git xidlehook betterlockscreen
fi
